### ISSUE TITLE
Change app display name to "Gitlab Ping"

### ISSUE THREAD

**Issue by tlimaf** [zaniluca/ping-4-gitlab#161]
Hello,

I'm trying to use this app, I see the name displayed on the iOS device after downloading is Ping instead of GitLab. I think at this point it's possible to change the name from Ping to GitLab to make it easier to identify and search.

Thanks for your app.

**Comment by tlimaf** [comment]
Or **GitLab Ping**.

**Comment by zaniluca** [comment]
@tlimaf Hi! Thank you for the feedback, at first I was going to set the app name as **Ping for Gitlab** but it didn't look great under the app icon, I think your second proposal may work fine

> Or **GitLab Ping**.

I'll try to add it in the next release or even the next update if its something that can be shipped over the air! thanks!
